# Generated by Django 5.2 on 2025-04-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disciplina',
            new_name='Disciplinas',
        ),
    ]
